### ISSUE TITLE
Fresh build fails game start: Cannot locate resource pssm_mat.material in resource group 

### ISSUE THREAD

**Issue by ShannonVanWagner** [RigsOfRods/rigs-of-rods#305]
An exception has occured!: OGRE EXCEPTION(6:FileNotFoundException): Cannot locate resource pssm_mat.material in resource group LoadBeforeMap or any other group. in ResourceGroupManager::openResource at /home/gamersteam/rigs-of-rods/source/sinbad-ogre-edccf8cc52e3/OgreMain/src/OgreResourceGroupManager.cpp (line 756) / url: http://wiki.rigsofrods.com/index.php?title=Error_6#ResourceGroupManager::openResource

**Comment by ShannonVanWagner** [comment]
Build date: Jul 8 2015 15:28:20

**Comment by Hiradur** [comment]
I think @Max98 removed PSSM shadows recently because they weren't working properly. To fix this error temporarily you can disable PSSM shadows.

**Comment by Max98** [comment]
@Hiradur That's the thing, I forget to remove them.. hahah
I'm about to release a fast fix for MP so I will include this.

**Comment by ShannonVanWagner** [comment]
Hi,
I set shadows to "No Shadows(fastest)" in the RoRConfig utility.
~/.rigsofrods/config/RoR.cfg shows this setting (apparently):
Shadow technique=No shadows (fastest)

But still the game was crashing with the same error.

So then I changed
~/rigs-of-rods/install/bin/resources/materials/managed.material
The line:
import * from "pssm_mat.material"
I commented out To:
#import * from "pssm_mat.material"

Now the game loads again.

Cheers!

**Comment by Max98** [comment]
managed.material should be deleted. I think there is a little conflict in the upstream.

**Comment by Hiradur** [comment]
With latest upstream I can't reproduce this issue.
You probably have to update your installation. Since I know you used my scripts you can do this simply by re-running RoRcore.sh

**Comment by ShannonVanWagner** [comment]
Hiradur@ - Hi, yes after I completed deleted my ~/rigs-of-rods dir, then rebuilt from your awesome scripts, the problem is resolved. I had re-ran RoRcore.sh previously, but for some reason it hadn't fixed the issue. I wonder.. would RoRcore.sh have triggered the managed.material file for deletion?

Thanks everyone for your time!

**Comment by Hiradur** [comment]
Usually you don't need to remove any directory when updating (only when the dependencies get updated which rarely happens). ```RoRcore.sh``` does ```git pull``` before it builds RoR again so it should sync with the upstream repository. If managed.materials was removed on upstream it should be deleted for you as well after running the script.

It may not have fixed the issue before because it wasn't fixed at the time you ran the script.
